# Generated by Django 2.2.4 on 2019-08-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190823_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
