# Generated by Django 2.2.4 on 2019-09-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190823_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='org_link',
            field=models.URLField(default='AUTO', null=True, unique=True),
        ),
    ]
