# Generated by Django 2.2.4 on 2019-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190924_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='test',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет'),
        ),
    ]
