# Generated by Django 2.2.4 on 2019-09-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190924_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='test',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3),
        ),
    ]
