# Generated by Django 2.2.4 on 2019-09-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190924_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount_restrictions',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='analytics',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='certification',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='co_ed',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='deadlines',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='disabled',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='facilitators_present',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='feedback',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='forums',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='individualization',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_counts',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='post_entrance',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='practice',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers_present',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutors_present',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='webinars',
            field=models.CharField(choices=[(True, 'Да'), (False, 'Нет')], default='Нет', max_length=3, null=True),
        ),
    ]
