# Generated by Django 2.2.4 on 2019-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190924_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_text_type',
            field=models.CharField(default='html', max_length=10),
        ),
    ]
