# Generated by Django 2.2.4 on 2019-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_detail_text_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_text_type',
            field=models.CharField(default='html', max_length=10),
        ),
    ]
